<!--  INF16B Maximilian Gerlach, Florian Schenk:added Header,Footer and Tags for CSS Styling-->
<jsp:include page="header.jsp" />
<div class=privacy>
        <h1>Datenschutzerkl&aumlrung</h1>
        <p>Der Schutz und die Sicherheit von pers&oumlnlichen Daten hat bei uns eine hohe Priorit&aumlt. Daher halten wir uns strikt an die Regeln des deutschen Bundesdatenschutzgesetzes (BDSG). Nachfolgend werden Sie dar&uumlber informiert, welche Art von Daten erfasst und zu welchem Zweck sie erhoben werden:</p>
        <p><h4>1. Daten&uumlbermittlung / Datenprotokollierung</h4>Beim Besuch dieser Seite verzeichnet der Web-Server automatisch Log-Files, die keiner bestimmten Person zugeordnet werden k&oumlnnen. Diese Daten beinhalten z. B. den Browsertyp und -version, verwendetes Betriebssystem, Referrer URL (die zuvor besuchte Seite), IP-Adresse des anfragenden Rechners, Zugriffsdatum und -uhrzeit der Serveranfrage und die Dateianfrage des Client (Dateiname und URL). Diese Daten werden nur zum Zweck der statistischen Auswertung gesammelt. Eine Weitergabe an Dritte, zu kommerziellen oder nichtkommerziellen Zwecken, findet nicht statt.</p>
        <p><h4>2. Nutzung pers&oumlnlicher Daten</h4>Pers&oumlnliche Daten werden nur erhoben oder verarbeitet, wenn Sie diese Angaben freiwillig, z.B. im Rahmen einer Anfrage mitteilen. Sofern keine erforderlichen Gr&uumlnde im Zusammenhang mit einer Gesch&aumlftsabwicklung bestehen, k&oumlnnen Sie jederzeit die zuvor erteilte Genehmigung Ihrer pers&oumlnlichen Datenspeicherung mit sofortiger Wirkung schriftlich (z.B. per E-Mail oder per Fax) widerrufen. Ihre Daten werden nicht an Dritte weitergeben, es sei denn, eine Weitergabe ist aufgrund gesetzlicher Vorschriften erforderlich.</p>
        <p><h4>3. Auskunft, &aumlnderung und L&oumlschung Ihrer Daten</h4>Gem&auml&szlig geltendem Recht k&oumlnnen Sie jederzeit bei uns schriftlich nachfragen, ob und welche personenbezogenen Daten bei uns &uumlber Sie gespeichert sind. Eine entsprechende Mitteilung hierzu erhalten Sie umgehend.</p>
        <p><h4>4. Sicherheit Ihrer Daten</h4>Ihre uns zur Verf&uumlgung gestellten pers&oumlnlichen Daten werden durch Ergreifung aller technischen sowie organisatorischen Sicherheitsma&szlignahmen so gesichert, dass sie f&uumlr den Zugriff unberechtigter Dritter unzug&aumlnglich sind. Bei Versendung von sehr sensiblen Daten oder Informationen ist es empfehlenswert, den Postweg zu nutzen, da eine vollst&aumlndige Datensicherheit per E-Mail nicht gew&aumlhrleistet werden kann.</p>
        <p><h4>5. Cookies</h4>Auf einigen unserer Seiten verwenden wir sog. "Session-Cookies", um Ihnen die Nutzung unserer Webseiten zu erleichtern. Dabei handelt es sich um kleine Textdateien, die nur f&uumlr die Dauer Ihres Besuchs unserer Webseite auf Ihrer Festplatte hinterlegt und abh&aumlngig von der Einstellung Ihres Browser-Programms beim Beenden des Browsers wieder gel&oumlscht werden. Diese Cookies rufen keine auf Ihrer Festplatte &uumlber Sie gespeicherten Informationen ab und beeintr&aumlchtigen nicht Ihren PC oder ihre Dateien. Die meisten Browser sind so eingestellt, dass sie Cookies automatisch akzeptieren. Sie k&oumlnnen das Speichern von Cookies jedoch deaktivieren oder ihren Browser so einstellen, dass er Sie auf die Sendung von Cookies hinweist.</p>
        <p><h4>6. &aumlnderungen dieser Datenschutzbestimmungen</h4>Wir werden diese Richtlinien zum Schutz Ihrer pers&oumlnlichen Daten von Zeit zu Zeit aktualisieren. Sie sollten sich diese Richtlinien gelegentlich ansehen, um auf dem Laufenden dar&uumlber zu bleiben, wie wir Ihre Daten sch&uumltzen und die Inhalte unserer Website stetig verbessern. Sollten wir wesentliche &aumlnderungen bei der Sammlung, der Nutzung und/oder der Weitergabe der uns von Ihnen zur Verf&uumlgung gestellten personenbezogenen Daten vornehmen, werden wir Sie durch einen eindeutigen und gut sichtbaren Hinweis auf der Website darauf aufmerksam machen. Mit der Nutzung der Webseite erkl&aumlren Sie sich mit den Bedingungen dieser Richtlinien zum Schutz pers&oumlnlicher Daten einverstanden.</p>
        <p>Bei Fragen zu diesen Datenschutzbestimmungen wenden Sie sich bitte &uumlber unsere Kontakt-Seite an uns.</p>
</div>
<jsp:include page="footer.jsp" />